# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.DeCAFS <- function(vectData, beta, lambda, gamma, phi = 0, type = "std") {
    .Call(`_DeCAFS_DeCAFS`, vectData, beta, lambda, gamma, phi, type)
}

.dataAR_c <- function(phi, epsilon0, mu, ynoise) {
    .Call(`_DeCAFS_dataAR_c`, phi, epsilon0, mu, ynoise)
}

