# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l2fpop <- function(vectData, l0penalty, l2penalty, gamma = 1.0, type = "std") {
    .Call(`_l2FPOP_l2fpop`, vectData, l0penalty, l2penalty, gamma, type)
}

dataAR_c <- function(gamma, y0, mu, ynoise) {
    .Call(`_l2FPOP_dataAR_c`, gamma, y0, mu, ynoise)
}

